In [1]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd

dataset = pd.read_csv("BreastCancerData.csv")

In [2]:
#starting values of dataset

print("dataset head")
print(dataset.head(5))


dataset head
         id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_wors

In [3]:
print(dataset.columns.values)

['id' 'diagnosis' 'radius_mean' 'texture_mean' 'perimeter_mean'
 'area_mean' 'smoothness_mean' 'compactness_mean' 'concavity_mean'
 'concave points_mean' 'symmetry_mean' 'fractal_dimension_mean'
 'radius_se' 'texture_se' 'perimeter_se' 'area_se' 'smoothness_se'
 'compactness_se' 'concavity_se' 'concave points_se' 'symmetry_se'
 'fractal_dimension_se' 'radius_worst' 'texture_worst' 'perimeter_worst'
 'area_worst' 'smoothness_worst' 'compactness_worst' 'concavity_worst'
 'concave points_worst' 'symmetry_worst' 'fractal_dimension_worst'
 'Unnamed: 32']


In [4]:
print(dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [5]:
print(dataset.describe())

                 id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813     

In [6]:
print(dataset.describe(include=['O']))

       diagnosis
count        569
unique         2
top            B
freq         357


In [7]:
X = dataset.iloc[:,2:32]
Y= dataset.iloc[:,1]

In [8]:
from sklearn.preprocessing import LabelEncoder

print("Before encoding")
print(Y[100:110])


labelencoder_Y = LabelEncoder()

Y=labelencoder_Y.fit_transform(Y)

print("After Encoding")

print(Y[100:110])

Before encoding
100    M
101    B
102    B
103    B
104    B
105    M
106    B
107    B
108    M
109    B
Name: diagnosis, dtype: object
After Encoding
[1 0 0 0 0 1 0 0 1 0]


In [9]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2, random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
# no of features + no of output nodes/ 2

from keras.models import Sequential
from keras.layers import Dense

classifier = Sequential()

classifier.add(Dense(units=16, kernel_initializer="uniform",activation="relu",input_dim=30))

classifier.add(Dense(units=8, kernel_initializer="uniform",activation="relu"))

classifier.add(Dense(units=6, kernel_initializer="uniform",activation="relu"))


classifier.add(Dense(units=1, kernel_initializer="uniform",activation="sigmoid"))

In [12]:
classifier.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])

In [13]:
classifier.fit(X_train,Y_train,batch_size=1,epochs=100)

Epoch 1/100
455/455 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.6879
Epoch 2/100
455/455 [==============================] - 1s 2ms/step - loss: 0.2090 - accuracy: 0.9582
Epoch 3/100
455/455 [==============================] - 1s 2ms/step - loss: 0.1034 - accuracy: 0.9692
Epoch 4/100
455/455 [==============================] - 1s 2ms/step - loss: 0.1071 - accuracy: 0.9714
Epoch 5/100
455/455 [==============================] - 1s 2ms/step - loss: 0.0994 - accuracy: 0.9758
Epoch 6/100
455/455 [==============================] - 1s 2ms/step - loss: 0.0934 - accuracy: 0.9802
Epoch 7/100
455/455 [==============================] - 1s 2ms/step - loss: 0.0981 - accuracy: 0.9824
Epoch 8/100
455/455 [==============================] - 1s 2ms/step - loss: 0.0886 - accuracy: 0.9824
Epoch 9/100
455/455 [==============================] - 1s 2ms/step - loss: 0.0938 - accuracy: 0.9846
Epoch 10/100
455/455 [==============================] - 1s 1ms/step - loss: 0.0947 - accura

In [14]:
from keras.models import load_model

classifier.save("breast_cancer_model1.h5")

C:\Users\swati yadav\anaconda3\Lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [15]:
y_pred=classifier.predict(X_test)
y_pred=[ 1 if y>=0.5 else 0 for y in y_pred]

4/4 [==============================] - 0s 2ms/step


In [16]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test,y_pred)

print(cm)

[[67  0]
 [ 2 45]]


In [17]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)
print(cm)

accuracy = (cm[0][0]+cm[1][1])/(cm[0][0]+cm[0][1]+cm[1][0]+cm[1][1])
print("Accuracy: "+ str(accuracy*100)+"%")

[[67  0]
 [ 2 45]]
Accuracy: 98.24561403508771%
